CentOS:
  "6.5":
    x86_64:
      us-east-1: "ami-f353449a"
      us-west-1: "ami-68f2cc2d"
      us-west-2: "ami-e091f8d0"
      eu-west-1: "ami-ef2bd598"
      ap-southeast-1: "ami-3a7a2a68"
      ap-southeast-2: "ami-bbd64e81"
      ap-northeast-1: "ami-13463b12"
      sa-east-1: "ami-2bdb7936"
